domain_path: D:\Vivado\control_bldc\kria_bldc_control\export\kria_bldc_control\sw\standalone_psu_cortexa53_0
app_src_dir: D:\Programas\AMDDesignTools\2025.2\Vitis\data\embeddedsw\lib\sw_apps\hello_world
template: hello_world
lang: c
