domain_path: D:\Vivado\KRIA_bldc_test\vitis_workspace\kd240_platform\zynqmp_fsbl\zynqmp_fsbl_bsp
app_src_dir: D:\Programas\Xilinx\2025.1\Vitis\data\embeddedsw\lib\sw_apps\zynqmp_fsbl
template: zynqmp_fsbl
lang: c
